name         'mcanevet-openldap'
version      '0.0.2'
dependency   'puppetlabs/stdlib'
source       'https://github.com/mcanevet/puppet-openldap'
author       'Mickaël Canévet'
summary      'Puppet OpenLDAP module'
project_page 'https://github.com/mcanevet/puppet-openldap'
