name         'camptocamp-openldap'
version      '0.1.2'
source       'https://github.com/camptocamp/puppet-openldap'
author       'Camptocamp'
summary      'Puppet OpenLDAP module'
license      'Apache-2.0'
project_page 'https://github.com/camptocamp/puppet-openldap'
description  'Puppet Openldap Module'

dependency   'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency   'domcleal/augeasproviders', '>=1.0.0 <2.0.0'
